version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: pim-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: pimdb
    ports:
      - "3306:3306"
    volumes:
      - pim_db_data:/var/lib/mysql
volumes:
  pim_db_data:
